In [3]:
import numpy as np

In [4]:
a = list(range(1000))
b = list(range(1000))

In [5]:
%%timeit
[2*x*x + 4*y for x in a for y in b]


179 ms ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
a = np.arange(1000)
b = np.arange(1000)

In [8]:
%%timeit
[2*a*a + 4*b]

5.96 µs ± 65.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
import numpy as np
a = np.arange(1, 76) 
print(a[::2])
a[::2] = -1              
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75]
[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1 24
 -1 26 -1 28 -1 30 -1 32 -1 34 -1 36 -1 38 -1 40 -1 42 -1 44 -1 46 -1 48
 -1 50 -1 52 -1 54 -1 56 -1 58 -1 60 -1 62 -1 64 -1 66 -1 68 -1 70 -1 72
 -1 74 -1]


In [10]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([3, 2])
print(np.setdiff1d(a, b))

[1 4 5 6 7 8 9]


4 задание

In [28]:
import random

n = np.random.randint(10, 100)
z = np.random.sample((n,n))
print(z)

print(z.sum())

maxi = z.max()
print(maxi)

z = z / maxi
print(z)
print(z - np.mean(z, axis = 1))

z[z == z.max()] = -1





[[0.56652104 0.08781745 0.82107887 ... 0.71666882 0.06398307 0.81820783]
 [0.77325018 0.93436929 0.43622885 ... 0.97485243 0.21185024 0.20929242]
 [0.14030355 0.51593148 0.75593553 ... 0.37627452 0.84961775 0.7713849 ]
 ...
 [0.92554054 0.13135735 0.74049718 ... 0.6897082  0.64041971 0.39560177]
 [0.79547592 0.78467814 0.51146495 ... 0.97310781 0.74996205 0.72507831]
 [0.13273017 0.6126756  0.24036743 ... 0.37922672 0.59727672 0.03134632]]
1724.031813670417
0.9994237427397198
[[0.56684769 0.08786808 0.82155229 ... 0.71708204 0.06401996 0.8186796 ]
 [0.77369603 0.93490803 0.43648037 ... 0.97541452 0.21197239 0.20941309]
 [0.14038445 0.51622896 0.75637139 ... 0.37649147 0.85010763 0.77182967]
 ...
 [0.9260742  0.13143309 0.74092414 ... 0.69010588 0.64078897 0.39582987]
 [0.79593458 0.78513058 0.51175985 ... 0.9736689  0.75039447 0.72549639]
 [0.1328067  0.61302886 0.24050603 ... 0.37944538 0.5976211  0.03136439]]
[[ 0.06468557 -0.42966733  0.26958939 ...  0.21466993 -0.45172403
   0.3124

array([[0.68132826, 0.01780194, 0.65454324, ..., 0.88935629, 0.23555487,
        0.21665002],
       [0.26819763, 0.18407761, 0.80636099, ..., 0.45333889, 0.57815729,
        0.1543612 ],
       [0.91974914, 0.21442992, 0.12379049, ..., 0.0326903 , 0.03543418,
        0.27712825],
       ...,
       [0.69330875, 0.91447732, 0.12408708, ..., 0.93873057, 0.96687379,
        0.03611056],
       [0.94772988, 0.6079719 , 0.17049862, ..., 0.25296868, 0.50764876,
        0.71676473],
       [0.18925159, 0.29340736, 0.22424235, ..., 0.27948612, 0.50830684,
        0.85122204]])

5 задание

In [ ]:
import numpy as np

def MeanMatrix(matrix):
    m = np.nanmean(matrix)
    matrix[np.isnan(matrix)] = (m, 0) [np.isnan(m)]

    return matrix

6 задание

In [29]:
an_array = np.random.rand(10)*20
print(an_array)
norm = np.linalg.norm(an_array)
normal_array = an_array/norm
print(normal_array)

[1.73328162 1.14713962 6.56908251 6.54308435 8.1406784  2.95204706
 7.43947963 0.79716585 1.82840832 2.28135657]
[0.11433912 0.07567318 0.43334166 0.43162665 0.53701489 0.19473724
 0.49075902 0.05258652 0.12061433 0.1504939 ]


7 задание

In [33]:
a = np.random.sample((10, 20, 5))
print(a)
np.save('example_1', a)
b = np.load('example_1.npy')
print(b)

[[[2.89210624e-01 8.18413639e-01 5.49638551e-01 9.41064466e-01
   8.11172888e-01]
  [3.81947337e-02 1.84880106e-01 3.16765065e-01 1.51220467e-01
   6.77600627e-01]
  [1.95495373e-01 4.23629221e-02 4.95999354e-01 9.89979401e-02
   8.40742744e-01]
  [4.55512402e-01 6.99142339e-01 6.19372323e-01 7.55272813e-01
   5.83009966e-01]
  [8.73610351e-01 7.63695710e-02 9.59833632e-01 2.93235521e-01
   8.07158599e-01]
  [4.14737965e-01 6.73978301e-01 8.60908537e-01 4.80198155e-01
   4.39665276e-01]
  [8.51877740e-01 4.04702168e-01 3.62733265e-01 2.66083531e-01
   3.73196637e-01]
  [3.58071211e-01 1.26181278e-01 3.76123747e-01 7.86894058e-02
   8.03140792e-01]
  [6.60830285e-01 3.39398652e-01 1.71893649e-01 5.45787904e-01
   5.27698294e-01]
  [6.25789045e-01 7.52265841e-01 1.99291722e-01 1.20330643e-01
   9.95142722e-01]
  [1.84452461e-01 8.95416678e-01 3.61221659e-01 6.70583500e-01
   6.76915647e-01]
  [3.01183138e-01 4.35759790e-01 8.78295512e-01 9.45032623e-01
   7.86797845e-01]
  [3.92124375e-0

8 задание

In [ ]:
import numpy as np

matrix = np.random.sample(1000) * 1000
v = int(input())
index = (np.abs(matrix-v)).argmin()
print(matrix[index])

9 задание

In [ ]:
import numpy as np

width, height, border, inside = list(map(int, input().split()))

matrix = np.full((height, width), border)
matrix[1:-1,1:-1] = inside

print(matrix)

10 задание

In [ ]:
import numpy as np
import sys

def matrixSort(matrix, column):
    order = (-matrix)[:, column].argsort()

    newMatrix = np.zeros((matrix.shape[0], matrix.shape[1]), dtype=int)
    for i in range(matrix.shape[1]):
        newMatrix[i] = matrix[order[i]]

    return newMatrix

column = int(input())
matrix = np.loadtxt(sys.stdin)
print(matrixSort(matrix, column))


11 задание

In [ ]:
import numpy as np


matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)